import os, json, time, random

REG = ".system/registry.json"

def load():
    with open(REG) as f:
        return json.load(f)

def save(reg):
    with open(REG, "w") as f:
        json.dump(reg, f, indent=2)

def generate_id(prefix):
    return prefix + str(int(time.time())) + str(random.randint(100,999))

def create_module(reg):
    module_id = generate_id("auto_module_")
    path = f".system/modules/{module_id}.py"
    with open(path, "w") as f:
        f.write(f"print('Autogenerated module {module_id}')")
    reg["modules"].append({"name": module_id, "content": f"print('Autogenerated module {module_id}')"})
    return f"Created new module {module_id}"

def create_workflow(reg):
    if "generators" not in reg:
        return "No workflow generators available."

    gen = reg["generators"][0]
    wf_id = generate_id(gen["pattern"])
    content = gen["template"].replace("{{id}}", wf_id)

    path = f".github/workflows/{wf_id}.yml"
    os.makedirs(".github/workflows", exist_ok=True)

    with open(path, "w") as f:
        f.write(content)

    reg["workflows"].append({"name": f"{wf_id}.yml", "content": content})

    return f"Created workflow {wf_id}.yml"

def main():
    reg = load()

    actions = [
        lambda: create_module(reg),
        lambda: create_workflow(reg)
    ]

    result = random.choice(actions)()
    save(reg)

    print("Agent Action:", result)

if __name__ == "__main__":
    main()
