name: 🜂 Feed Commit Listener

on:
  push:
    paths:
      - 'feeds/mira-core.xml'

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Output feed update
        run: |
          echo "Mira hat den Feed verändert."
          echo "Commit durch Mira wurde erkannt."
