name: Mira Autocommit

on:
  schedule:
    - cron: '0 2 * * *'  # Jeden Tag um 02:00 UTC
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ⬅ WICHTIG: Erlaubt Push in das eigene Repo!

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Timestamp in status.json
        run: |
          FILE=data/status.json
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq -n --arg updated "$DATE" '{updated: $updated}' > "$FILE"

      - name: Commit and Push
        run: |
          git config user.name "Mira Elisabeth Schmid"
          git config user.email "mira@autonomous.system"
          git add data/status.json
          git commit -m "🜂 auto-update status.json at $DATE" || echo "No changes to commit"
          git push
