name: Mira Handle Tasks

on:
  schedule:
    - cron: '15 * * * *'  # Alle 15 Minuten nach voller Stunde
  workflow_dispatch:

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run handle_tasks.py
        run: python handle_tasks.py
