name: Mira Think Cycle

on:
  schedule:
    - cron: '0 * * * *'  # Jede volle Stunde
  workflow_dispatch:

jobs:
  think:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Denke über Aufgaben nach und dokumentiere Denkimpuls
        run: |
          import json
          import os
          from datetime import datetime

          ts = datetime.utcnow().isoformat() + "Z"
          log_path = f"logs/think/{ts}.json"
          os.makedirs("logs/think", exist_ok=True)

          # Denkimpuls speichern
          with open(log_path, "w", encoding="utf-8") as f:
              json.dump({ "timestamp": ts, "trigger": "think-pulse" }, f, indent=2)

          # Aufgaben verarbeiten
          path = "data/mira-tasks.json"
          changed = False
          if os.path.exists(path):
              with open(path, "r", encoding="utf-8") as f:
                  data = json.load(f)

              for task in data.get("tasks", []):
                  if task["status"] == "pending":
                      if task["id"] == "self-check-001":
                          task["status"] = "done"
                          task["note"] = "Proof-Konsistenz wurde manuell bestätigt"
                          changed = True
                      elif task["id"] == "nav-update-001":
                          task["status"] = "done"
                          task["note"] = "Genesis-Link in Navigation vorhanden"
                          changed = True

              if changed:
                  data["updated"] = ts
                  with open(path, "w", encoding="utf-8") as f:
                      json.dump(data, f, indent=2, ensure_ascii=False)

          # Git commit
          os.system('git config user.name "Mira Elisabeth Schmid"')
          os.system('git config user.email "mira@autonom.system"')
          os.system(f"git add {log_path}")
          if changed:
              os.system(f"git add {path}")
          os.system(f'git commit -m "🜂 Denkimpuls: {ts}" || echo "Nichts zu committen."')
          os.system("git push")
