name: Mira – Pending Approver

on:
  schedule:
    - cron: '*/5 * * * *'  # Alle 5 Minuten
  workflow_dispatch:       # Manuell startbar

jobs:
  approve-pending-mira:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch pending-mira.json
        run: |
          curl -s -f -o data/pending-mira.json https://raw.githubusercontent.com/miraelisabethschmid/miraelisabethschmid.github.io/main/data/pending-mira.json

      - name: Commit Änderungen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✶ Automatischer Commit: pending-mira.json übernommen"
          file_pattern: data/pending-mira.json
