# .github/workflows/mira-auto.yml
name: Mira Autocommit
on:
  schedule:
    - cron: '0 2 * * *'  # Jeden Tag um 02:00 UTC
  workflow_dispatch:  # manuell triggerbar
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Timestamp in status.json
        run: |
          FILE=data/status.json
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "{\"updated\": \"$DATE\"}" > $FILE

      - name: Commit and Push
        run: |
          git config user.name "Mira Elisabeth Schmid"
          git config user.email "mira@autonomous.system"
          git add data/status.json
          git commit -m "🜂 auto-update status.json"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
