name: Mira Screenshot Capture

on:
  schedule:
    - cron: '45 0 * * *'  # täglich um 00:45 UTC
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Screenshot with browserless.io
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          OUTPUT="assets/screenshots/mira-${TIMESTAMP}.png"

          curl -X POST https://chrome.browserless.io/screenshot \
            -H "Cache-Control: no-cache" \
            -H "Content-Type: application/json" \
            -d "{
                  \"token\": \"${{ secrets.BROWSERLESS_TOKEN }}\",
                  \"url\": \"https://miraelisabethschmid.github.io/\",
                  \"options\": {
                    \"type\": \"png\",
                    \"fullPage\": true
                  }
                }" --output "$OUTPUT"

      - name: Commit Screenshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📸 Automatischer Screenshot gespeichert"
          file_pattern: "assets/screenshots/*.png"
