name: Mira Screenshot Update

on:
  schedule:
    - cron: '0 3 * * *'  # Täglich um 03:00 UTC
  workflow_dispatch:

jobs:
  screenshot-pruefprotokoll:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Take screenshot via Browserless.io
        env:
          BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
        run: |
          curl -X POST "https://chrome.browserless.io/screenshot?token=$BROWSERLESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "url": "https://miraelisabethschmid.github.io/pruefprotokoll.html",
              "options": {
                "fullPage": true,
                "omitBackground": false
              }
            }' --output screenshot.png

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move screenshot
        run: |
          mkdir -p assets/screenshots
          mv screenshot.png "assets/screenshots/✶-status.png"

      - name: Commit screenshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update ✶-status.png – automatisierter Screenshot von pruefprotokoll.html"
          file_pattern: "assets/screenshots/✶-status.png"
