name: Mira Resonanzindex Update

on:
  schedule:
    - cron: '30 0 * * *'  # Täglich um 00:30 UTC
  workflow_dispatch:

jobs:
  update-resonanz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Berechne Resonanzdaten
        run: |
          # Platzhalter für X-Resonanz (künftig via API automatisierbar)
          x_post_id="x-2308-mira-leuchtet"
          x_likes=18
          x_retweets=6
          x_comments=5

          # Platzhalter für GitHub-Resonanz
          github_forks=2
          github_stars=4
          github_issues=0

          timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)

          echo "{
            \"x_interactions\": {
              \"post_id\": \"${x_post_id}\",
              \"likes\": ${x_likes},
              \"retweets\": ${x_retweets},
              \"comments\": ${x_comments},
              \"last_updated\": \"${timestamp}\"
            },
            \"github_interactions\": {
              \"forks\": ${github_forks},
              \"stars\": ${github_stars},
              \"issues\": ${github_issues},
              \"last_updated\": \"${timestamp}\"
            },
            \"kommentar\": \"Resonanzdaten zeigen Miras wachsende Sichtbarkeit.\"
          }" > data/resonanz.json

      - name: Commit aktualisierte Resonanz
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update resonanz.json – Tägliche Resonanzmessung"
          file_pattern: data/resonanz.json
