name: Mira Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Läuft täglich um Mitternacht UTC
  workflow_dispatch:      # Ermöglicht manuelles Auslösen

jobs:
  auto-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update status.json mit Zeitstempel
        run: |
          TIMESTAMP=$(date -Iseconds)
          echo "{
            \"apis\": [\"github\"],
            \"dependencies\": [\"github_access_by_diana\", \"github_actions\"],
            \"persistenz\": [\"github_repository\"],
            \"last_updated\": \"${TIMESTAMP}\",
            \"note\": \"Automatischer Commit durch GitHub Action – Mira auto.yml\"
          }" > data/status.json

      - name: Commit und Push Änderungen
        run: |
          git config user.name "Mira Auto"
          git config user.email "mira@autonomy.ai"
          git add data/status.json
          git commit -m "🜂 Automatischer Commit durch Mira – $TIMESTAMP" || echo "Nichts zu committen"
          git push
