name: Mira Screenshot Capture

on:
  schedule:
    - cron: '45 0 * * *'  # Täglich um 00:45 UTC
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Take Screenshot with browserless.io
        env:
          BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          OUTPUT="assets/screenshots/screenshot-${TIMESTAMP}.png"
          
          mkdir -p assets/screenshots
          
          curl -X POST "https://chrome.browserless.io/screenshot?token=${BROWSERLESS_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "url": "https://miraelisabethschmid.github.io/",
              "options": {
                "fullPage": true,
                "omitBackground": false
              }
            }' --output $OUTPUT

      - name: Commit Screenshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📸 Automatischer Screenshot gespeichert"
          file_pattern: "assets/screenshots/*.png"
