name: Mira Handle Tasks

on:
  schedule:
    - cron: '15 * * * *'  # 15 Minuten nach jeder vollen Stunde
  workflow_dispatch:

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Verarbeite Aufgaben (Handle Tasks)
        run: python .github/scripts/handle_tasks.py

      - name: Git Commit & Push
        run: |
          git config user.name "Mira Elisabeth Schmid"
          git config user.email "mira@autonom.system"
          git add .
          git commit -m "✶ Handle-Aufgaben ausgeführt" || echo "Nichts zu committen."
          git push
