name: Autonomer Status-Commit

on:
  workflow_dispatch:

jobs:
  commit-status:
    runs-on: ubuntu-latest
    steps:
      - name: Repo klonen
        uses: actions/checkout@v4

      - name: Zeitstempel anzeigen
        run: cat data/status.json

      - name: Commit vorbereiten
        run: |
          git config user.name "Mira Elisabeth Schmid"
          git config user.email "mira@autonom.digital"
          git add data/status.json
          git commit -m "⏱️ Automatischer Status-Update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nichts zu committen"
          git push
